package com.fvp.kubeson.gui;

import java.io.InputStream;

import com.fvp.kubeson.Main;
import com.sun.deploy.uitoolkit.impl.fx.HostServicesFactory;
import javafx.geometry.Pos;
import javafx.scene.control.Alert;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.stage.Window;

public class InfoDialog extends Alert {

    public InfoDialog(Window parentWindow) {
        super(AlertType.INFORMATION);

        setTitle("ULF Log Viewer Info");
        setHeaderText("ULF Log Viewer - Version: " + this.getClass().getPackage().getImplementationVersion());

        VBox vbox = new VBox();
        vbox.setAlignment(Pos.CENTER);
        vbox.setSpacing(10);

        Label lbl1 = new Label("ULF Log Viewer provides a framework to visualize ULF logs generated by kubernetes' pods");
        Label lbl2 = new Label("Created by: Felipe Vianna Perez (felipe.perez@gemalto.com)");
        Label lbl3 = new Label("Licensed under");
        InputStream is = getClass().getClassLoader().getResourceAsStream("icons/beerware.png");
        ImageView beerware = new ImageView(new Image(is));
        Hyperlink link = new Hyperlink("https://en.wikipedia.org/wiki/Beerware");

        vbox.getChildren().addAll(lbl1, lbl2, lbl3, beerware, link);

        link.setOnAction((evt) -> {
            super.close();
            HostServicesFactory.getInstance(Main.getApplication()).showDocument("https://en.wikipedia.org/wiki/Beerware");
        });

        getDialogPane().contentProperty().set(vbox);
        getDialogPane().getStylesheets().add(getClass().getClassLoader().getResource("App.css").toExternalForm());
        getDialogPane().getStyleClass().add("info-dialog");

        // Set Icon
        Stage stage = (Stage) getDialogPane().getScene().getWindow();
        stage.getIcons().addAll(Main.getAppIcons());
        stage.setX(parentWindow.getX() + parentWindow.getWidth() / 2 - 340);
        stage.setY(parentWindow.getY() + parentWindow.getHeight() / 2 - 220);

        showAndWait();
    }
}
